import * as V from '../dsp/biquad';

export const SAMPLE_RATE = 44100;

export interface FreqBand {
  id: string;
  name: string;
  short: string;
  fLow: number;
  fHigh: number;
  fill: string;
  fillHover: string;
  labelColor: string;
}

// Fills tuned for a light cream background (subtle washes, stronger on hover).
export const FREQ_BANDS: FreqBand[] = [
  { id: 'sub', name: 'Sub bass', short: 'Sub', fLow: 20, fHigh: 80, fill: 'rgba(124,58,237,0.10)', fillHover: 'rgba(124,58,237,0.22)', labelColor: '#6d28d9' },
  { id: 'bass', name: 'Mid bass', short: 'Mid bass', fLow: 80, fHigh: 300, fill: 'rgba(37,99,235,0.09)', fillHover: 'rgba(37,99,235,0.20)', labelColor: '#1d4ed8' },
  { id: 'lowmid', name: 'Lower midrange', short: 'Lower mid', fLow: 300, fHigh: 2000, fill: 'rgba(5,150,105,0.09)', fillHover: 'rgba(5,150,105,0.20)', labelColor: '#047857' },
  { id: 'upmid', name: 'Upper midrange', short: 'Upper mid', fLow: 2000, fHigh: 8000, fill: 'rgba(217,119,6,0.10)', fillHover: 'rgba(217,119,6,0.22)', labelColor: '#b45309' },
  { id: 'treble', name: 'Treble', short: 'Treble', fLow: 8000, fHigh: 12000, fill: 'rgba(220,38,38,0.09)', fillHover: 'rgba(220,38,38,0.20)', labelColor: '#b91c1c' },
  { id: 'air', name: 'Air', short: 'Air', fLow: 12000, fHigh: 20000, fill: 'rgba(8,145,178,0.10)', fillHover: 'rgba(8,145,178,0.22)', labelColor: '#0e7490' },
];

export type FilterType = 'peak' | 'lowShelf' | 'highShelf' | 'lowPass' | 'highPass' | 'notch';

export interface EQBandDef {
  id: string;
  enabled: boolean;
  type: FilterType;
  frequency: number;
  gain: number;
  q: number;
}

export interface DeviceProfile {
  id: string;
  name: string;
  brand: string;
  deviceType: 'iem' | 'headphone';
  filters: Array<{ type: FilterType; freq: number; gain: number; q: number }>;
}

export interface TargetProfile {
  id: string;
  name: string;
  filters: Array<{ type: FilterType; freq: number; gain: number; q: number }>;
}

// squig.link (CrinGraph) listener palette — generated by its golden-ratio HCL
// sequence and ordered for distinctness/legibility on a light background.
export const DEVICE_COLORS = [
  '#0070c5', '#ff001f', '#008a6c', '#e48f00',
  '#95009e', '#00ac00', '#003a9d', '#cac100',
];

function clamp(v: number, lo: number, hi: number) {
  return Math.max(lo, Math.min(hi, v));
}

// Coeficientes do biquad. Os tipos cobertos pelo backend `lemi` (peaking e os
// dois shelves) usam o DSP formalmente verificado via facade ../dsp/biquad
// (WebAssembly quando disponível, senão a porta TS). Os demais
// (lowPass/highPass/notch) seguem o RBJ padrão.
// Peaking usa Q; os shelves usam a inclinação S ∈ (0,1] (o campo Q da banda é
// reaproveitado como S e limitado a esse intervalo).
function biquadCoeffs(type: FilterType, freq: number, gain: number, q: number) {
  const f = clamp(freq, 1, SAMPLE_RATE / 2 - 1);

  switch (type) {
    case 'peak':
      return { ...V.peaking(f, SAMPLE_RATE, Math.max(0.001, q), gain), a0: 1 };
    case 'lowShelf':
      return { ...V.lowShelf(f, SAMPLE_RATE, clamp(q, 0.001, 1), gain), a0: 1 };
    case 'highShelf':
      return { ...V.highShelf(f, SAMPLE_RATE, clamp(q, 0.001, 1), gain), a0: 1 };
  }

  // Tipos não cobertos pelo backend (RBJ Cookbook padrão).
  const w0 = 2 * Math.PI * f / SAMPLE_RATE;
  const cw = Math.cos(w0), sw = Math.sin(w0);
  const alpha = sw / (2 * Math.max(0.001, q));
  switch (type) {
    case 'lowPass':
      return { b0: (1-cw)/2, b1: 1-cw, b2: (1-cw)/2, a0: 1+alpha, a1: -2*cw, a2: 1-alpha };
    case 'highPass':
      return { b0: (1+cw)/2, b1: -(1+cw), b2: (1+cw)/2, a0: 1+alpha, a1: -2*cw, a2: 1-alpha };
    case 'notch':
      return { b0: 1, b1: -2*cw, b2: 1, a0: 1+alpha, a1: -2*cw, a2: 1-alpha };
  }
  // inalcançável (FilterType é exaustivo); satisfaz o verificador de tipos.
  return { b0: 1, b1: 0, b2: 0, a0: 1, a1: 0, a2: 0 };
}

function biquadResponse(c: ReturnType<typeof biquadCoeffs>, f: number): number {
  const w = 2 * Math.PI * f / SAMPLE_RATE;
  const cw = Math.cos(w), c2w = Math.cos(2*w), sw = Math.sin(w), s2w = Math.sin(2*w);
  const { b0, b1, b2, a0, a1, a2 } = c;
  const nr = b0 + b1*cw + b2*c2w, ni = -(b1*sw + b2*s2w);
  const dr = a0 + a1*cw + a2*c2w, di = -(a1*sw + a2*s2w);
  const dSq = dr*dr + di*di;
  return dSq === 0 ? 0 : 10 * Math.log10((nr*nr + ni*ni) / dSq);
}

function getLogFreqs(n = 600): number[] {
  const lMin = Math.log10(20), lMax = Math.log10(20000);
  return Array.from({ length: n }, (_, i) => 10 ** (lMin + (i / (n-1)) * (lMax - lMin)));
}

export const LOG_FREQS = getLogFreqs(600);

export function calcProfileCurve(
  filters: Array<{ type: FilterType; freq: number; gain: number; q: number }>,
  freqs: number[]
): number[] {
  if (filters.length === 0) return freqs.map(() => 0);
  const coeffsList = filters.map(f => biquadCoeffs(f.type, f.freq, f.gain, f.q));
  return freqs.map(f => coeffsList.reduce((s, c) => s + biquadResponse(c, f), 0));
}

export function calcEQCurve(bands: EQBandDef[], freqs: number[]): number[] {
  const active = bands.filter(b => b.enabled);
  if (active.length === 0) return freqs.map(() => 0);
  const coeffsList = active.map(b => biquadCoeffs(b.type, b.frequency, b.gain, b.q));
  return freqs.map(f => coeffsList.reduce((s, c) => s + biquadResponse(c, f), 0));
}

export function exportEqualizerAPO(bands: EQBandDef[], preamp = -6): string {
  const active = bands.filter(b => b.enabled);
  const typeMap: Record<FilterType, string> = {
    peak: 'PK', lowShelf: 'LSC', highShelf: 'HSC',
    lowPass: 'LPQ', highPass: 'HPQ', notch: 'NO',
  };
  const lines = [`Preamp: ${preamp >= 0 ? '+' : ''}${preamp.toFixed(1)} dB`];
  active.forEach((b, i) => {
    const hasGain = b.type !== 'lowPass' && b.type !== 'highPass' && b.type !== 'notch';
    const gainStr = hasGain ? ` Gain ${b.gain >= 0 ? '+' : ''}${b.gain.toFixed(1)} dB` : '';
    lines.push(`Filter ${i+1}: ON ${typeMap[b.type]} Fc ${Math.round(b.frequency)} Hz${gainStr} Q ${b.q.toFixed(2)}`);
  });
  return lines.join('\n');
}

// Suggested preamp to avoid clipping: negative of the largest positive gain.
export function suggestPreamp(bands: EQBandDef[]): number {
  const maxBoost = bands.filter(b => b.enabled).reduce((m, b) => Math.max(m, b.gain), 0);
  return Math.round(-maxBoost * 10) / 10 || 0;
}

export interface EQPreset {
  id: string;
  name: string;
  description: string;
  bands: Array<Omit<EQBandDef, 'id'>>;
}

const peak = (frequency: number, gain: number, q = 1.0): Omit<EQBandDef, 'id'> => ({ enabled: true, type: 'peak', frequency, gain, q });
const lowS = (frequency: number, gain: number, q = 0.7): Omit<EQBandDef, 'id'> => ({ enabled: true, type: 'lowShelf', frequency, gain, q });
const hiS = (frequency: number, gain: number, q = 0.7): Omit<EQBandDef, 'id'> => ({ enabled: true, type: 'highShelf', frequency, gain, q });

export const EQ_PRESETS: EQPreset[] = [
  { id: 'flat', name: 'Flat', description: 'Sem equalização', bands: [] },
  { id: 'bass', name: 'Bass Boost', description: 'Reforço de graves', bands: [lowS(90, 6), peak(60, 3, 0.8)] },
  { id: 'treble', name: 'Treble Boost', description: 'Reforço de agudos', bands: [hiS(8000, 5), peak(12000, 3, 1.0)] },
  { id: 'vshape', name: 'V-Shape', description: 'Graves e agudos realçados', bands: [lowS(90, 5), peak(1500, -2.5, 1.0), hiS(9000, 5)] },
  { id: 'vocal', name: 'Vocal', description: 'Voz à frente', bands: [peak(250, -2, 1.0), peak(3000, 3, 1.2), hiS(10000, -2)] },
  { id: 'warm', name: 'Warm', description: 'Quente e suave', bands: [lowS(120, 3), peak(3500, -2, 1.2), hiS(7000, -3)] },
  { id: 'bright', name: 'Bright', description: 'Brilhante e detalhado', bands: [peak(2500, 2.5, 1.0), hiS(8000, 4)] },
  { id: 'loudness', name: 'Loudness', description: 'Curva de baixo volume', bands: [lowS(60, 6), peak(2000, -1.5, 1.0), hiS(10000, 4)] },
  { id: 'podcast', name: 'Podcast', description: 'Fala clara', bands: [peak(100, -3, 0.8), peak(300, -2, 1.0), peak(2800, 3, 1.2), hiS(9000, -3)] },
];

export const DEVICE_PROFILES: DeviceProfile[] = [
  { id: 'moondrop-aria', name: 'Aria', brand: 'Moondrop', deviceType: 'iem', filters: [
    { type: 'lowShelf', freq: 180, gain: 2.5, q: 0.7 },
    { type: 'peak', freq: 3400, gain: 5.5, q: 1.4 },
    { type: 'peak', freq: 6200, gain: -7.0, q: 2.2 },
    { type: 'peak', freq: 8800, gain: 3.5, q: 2.8 },
    { type: 'highShelf', freq: 13000, gain: -5.0, q: 0.8 },
  ]},
  { id: '7hz-zero', name: 'Salnotes Zero', brand: '7Hz', deviceType: 'iem', filters: [
    { type: 'lowShelf', freq: 120, gain: 0.5, q: 0.7 },
    { type: 'peak', freq: 3200, gain: 4.5, q: 1.5 },
    { type: 'peak', freq: 6000, gain: -5.5, q: 2.0 },
    { type: 'peak', freq: 8500, gain: 2.5, q: 3.0 },
    { type: 'highShelf', freq: 12000, gain: -6.5, q: 0.9 },
  ]},
  { id: 'blessing2', name: 'Blessing 2', brand: 'Moondrop', deviceType: 'iem', filters: [
    { type: 'lowShelf', freq: 130, gain: 1.5, q: 0.7 },
    { type: 'peak', freq: 4000, gain: 6.0, q: 1.2 },
    { type: 'peak', freq: 5800, gain: -5.0, q: 1.8 },
    { type: 'peak', freq: 9000, gain: 5.0, q: 2.5 },
    { type: 'highShelf', freq: 14000, gain: -3.5, q: 0.8 },
  ]},
  { id: 'letshuoer-s12', name: 'S12 Pro', brand: 'Letshuoer', deviceType: 'iem', filters: [
    { type: 'lowShelf', freq: 160, gain: 3.0, q: 0.7 },
    { type: 'peak', freq: 3800, gain: 5.0, q: 1.3 },
    { type: 'peak', freq: 6500, gain: -6.0, q: 2.0 },
    { type: 'peak', freq: 9500, gain: 4.0, q: 2.5 },
    { type: 'highShelf', freq: 13500, gain: -4.0, q: 0.8 },
  ]},
  { id: 'truthear-zero', name: 'Zero', brand: 'Truthear', deviceType: 'iem', filters: [
    { type: 'lowShelf', freq: 150, gain: 4.0, q: 0.7 },
    { type: 'peak', freq: 3500, gain: 5.0, q: 1.3 },
    { type: 'peak', freq: 6200, gain: -6.5, q: 2.2 },
    { type: 'peak', freq: 9000, gain: 3.0, q: 2.8 },
    { type: 'highShelf', freq: 13000, gain: -4.5, q: 0.8 },
  ]},
  { id: 'dunu-titan-s', name: 'Titan S', brand: 'DUNU', deviceType: 'iem', filters: [
    { type: 'lowShelf', freq: 140, gain: 1.5, q: 0.7 },
    { type: 'peak', freq: 3600, gain: 4.5, q: 1.4 },
    { type: 'peak', freq: 6000, gain: -4.5, q: 2.3 },
    { type: 'peak', freq: 9500, gain: 3.5, q: 2.5 },
    { type: 'highShelf', freq: 14000, gain: -3.0, q: 0.8 },
  ]},
  { id: 'er2xr', name: 'ER2XR', brand: 'Etymotic', deviceType: 'iem', filters: [
    { type: 'lowShelf', freq: 100, gain: 1.0, q: 0.7 },
    { type: 'peak', freq: 3000, gain: 3.0, q: 1.8 },
    { type: 'peak', freq: 6500, gain: -2.0, q: 2.5 },
    { type: 'highShelf', freq: 10000, gain: -4.5, q: 0.8 },
  ]},
  { id: 'kz-zex-pro', name: 'ZEX Pro', brand: 'KZ', deviceType: 'iem', filters: [
    { type: 'lowShelf', freq: 200, gain: 5.5, q: 0.7 },
    { type: 'peak', freq: 3500, gain: 4.0, q: 1.2 },
    { type: 'peak', freq: 5800, gain: -8.0, q: 2.0 },
    { type: 'peak', freq: 9000, gain: 2.5, q: 3.0 },
    { type: 'highShelf', freq: 12000, gain: -7.0, q: 0.9 },
  ]},
  { id: 'hd600', name: 'HD 600', brand: 'Sennheiser', deviceType: 'headphone', filters: [
    { type: 'lowShelf', freq: 100, gain: -3.0, q: 0.7 },
    { type: 'peak', freq: 3500, gain: 3.0, q: 1.5 },
    { type: 'peak', freq: 5500, gain: -3.5, q: 2.0 },
    { type: 'peak', freq: 8000, gain: 6.0, q: 2.5 },
    { type: 'highShelf', freq: 12000, gain: -8.0, q: 0.8 },
  ]},
  { id: 'hd800s', name: 'HD 800S', brand: 'Sennheiser', deviceType: 'headphone', filters: [
    { type: 'lowShelf', freq: 100, gain: -4.5, q: 0.7 },
    { type: 'peak', freq: 3200, gain: 2.5, q: 1.6 },
    { type: 'peak', freq: 5800, gain: -2.0, q: 1.8 },
    { type: 'peak', freq: 8500, gain: 7.0, q: 2.0 },
    { type: 'peak', freq: 12000, gain: -5.0, q: 1.5 },
    { type: 'highShelf', freq: 15000, gain: -6.0, q: 0.8 },
  ]},
  { id: 'wh1000xm5', name: 'WH-1000XM5', brand: 'Sony', deviceType: 'headphone', filters: [
    { type: 'lowShelf', freq: 200, gain: 7.0, q: 0.7 },
    { type: 'peak', freq: 1000, gain: -1.5, q: 1.0 },
    { type: 'peak', freq: 3500, gain: 2.5, q: 1.5 },
    { type: 'peak', freq: 6500, gain: -3.0, q: 2.0 },
    { type: 'highShelf', freq: 10000, gain: -4.0, q: 0.8 },
  ]},
  { id: 'dt900-pro-x', name: 'DT 900 Pro X', brand: 'Beyerdynamic', deviceType: 'headphone', filters: [
    { type: 'lowShelf', freq: 100, gain: -1.5, q: 0.7 },
    { type: 'peak', freq: 3500, gain: 3.5, q: 1.4 },
    { type: 'peak', freq: 6000, gain: -2.5, q: 2.0 },
    { type: 'peak', freq: 9000, gain: 5.5, q: 2.2 },
    { type: 'highShelf', freq: 13000, gain: -4.0, q: 0.8 },
  ]},
];

export function computeAutoEQ(
  deviceFilters: Array<{ type: FilterType; freq: number; gain: number; q: number }>,
  targetFilters: Array<{ type: FilterType; freq: number; gain: number; q: number }>,
  startId = 0
): EQBandDef[] {
  const deviceCurve = calcProfileCurve(deviceFilters, LOG_FREQS);
  const targetCurve = calcProfileCurve(targetFilters, LOG_FREQS);
  const error = LOG_FREQS.map((_, i) => targetCurve[i] - deviceCurve[i]);

  // Smooth with moving average in log-freq space
  const W = 25;
  const smoothed = error.map((_, i) => {
    const lo = Math.max(0, i - W), hi = Math.min(LOG_FREQS.length - 1, i + W);
    let s = 0; for (let j = lo; j <= hi; j++) s += error[j];
    return s / (hi - lo + 1);
  });

  const centers = [40, 80, 160, 320, 630, 1250, 2500, 5000, 10000, 16000];
  const qs = [0.6, 0.7, 0.8, 1.0, 1.2, 1.4, 1.5, 1.6, 1.8, 2.0];

  return centers.map((fc, i) => {
    const fLow = fc / Math.pow(2, 0.5), fHigh = fc * Math.pow(2, 0.5);
    let sum = 0, count = 0;
    for (let j = 0; j < LOG_FREQS.length; j++) {
      if (LOG_FREQS[j] >= fLow && LOG_FREQS[j] <= fHigh) { sum += smoothed[j]; count++; }
    }
    const gain = count > 0 ? Math.max(-12, Math.min(12, sum / count)) : 0;
    return {
      id: `auto_${startId + i}`,
      enabled: Math.abs(gain) >= 0.5,
      type: 'peak' as FilterType,
      frequency: fc,
      gain: Math.round(gain * 10) / 10,
      q: qs[i],
    };
  });
}

export const TARGET_CURVES: TargetProfile[] = [
  { id: 'harman-iem-2019', name: 'Harman IEM 2019', filters: [
    { type: 'lowShelf', freq: 105, gain: 3.0, q: 0.7 },
    { type: 'peak', freq: 3500, gain: 3.5, q: 1.5 },
    { type: 'peak', freq: 6000, gain: -3.0, q: 2.0 },
    { type: 'highShelf', freq: 10000, gain: -7.0, q: 0.8 },
  ]},
  { id: 'harman-oe-2018', name: 'Harman OE 2018', filters: [
    { type: 'lowShelf', freq: 120, gain: 5.0, q: 0.7 },
    { type: 'peak', freq: 3500, gain: 3.5, q: 1.5 },
    { type: 'peak', freq: 6000, gain: -3.5, q: 2.0 },
    { type: 'highShelf', freq: 10000, gain: -6.0, q: 0.8 },
  ]},
  { id: 'ief-neutral', name: 'IEF Neutral 2023', filters: [
    { type: 'lowShelf', freq: 100, gain: 1.0, q: 0.7 },
    { type: 'peak', freq: 3200, gain: 4.0, q: 1.5 },
    { type: 'peak', freq: 6500, gain: -4.0, q: 2.2 },
    { type: 'highShelf', freq: 10000, gain: -9.0, q: 0.8 },
  ]},
  { id: 'diffuse-field', name: 'Diffuse Field', filters: [
    { type: 'lowShelf', freq: 100, gain: -3.5, q: 0.7 },
    { type: 'peak', freq: 3200, gain: 4.5, q: 1.5 },
    { type: 'peak', freq: 8500, gain: 4.0, q: 2.0 },
    { type: 'highShelf', freq: 12000, gain: -3.0, q: 0.8 },
  ]},
];
